spring:
  application:
    name: project
  batch:
    job:
      enabled: false  # 앱 시작시 배치 자동실행 끄기
    jdbc:
      initialize-schema: never  
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}         # 비밀번호 없으면 빈 값 유지
  datasource:
    url: ${DATA_BASE_URL}
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          exception-handling: ignore
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: sdf
            client-secret: asdsd
            authorization-grant-type: authorization_code
            scope:
              - email
              - gender
              - birthday
              - birthyear
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              #- gender
              #- birthday
              #- birthyear
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_accou
  rabbitmq:
    host: rabbitmq
    password: ${RABBIT_PASSWORD}
    port: 5672
    username: guest
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

jwt:
  issuer: test
  secret-key: ${JWT_SECRET_KEY}

discord:
  mq-url:

climate:
  api-key:
  api-url: https://apihub.kma.go.kr/api/typ02/openApi/VilageFcstInfoService_2.0/getVilageFcst

api-key:
  odsay: ${ODSAY}
  korea-data-portal: ${KOREA_DATA_PORTAL}


bus:
  api:
    arrival:
      seoul-url: http://ws.bus.go.kr/api/rest/arrive/getArrInfoByRoute
      gbis-url: http://apis.data.go.kr/6410000/busarrivalservice/v2/getBusArrivalItemv2
    station-ord:
      gbis-url: http://apis.data.go.kr/6410000/busrouteservice/v2/getBusRouteStationListv2
      seoul-url: http://ws.bus.go.kr/api/rest/busRouteInfo/getStaionByRoute
firebase:
  config-path: ${FIREBASE_TOKEN_PATH}

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: "prometheus"
fcm:
  image: ${FCM_IMAGE}

ga4:
  measurement-id: ${GA4_MEASUREMENT_ID}
  api-secret: ${GA4_API_SECRET}
